#!/usr/bin/env bash
set -euo pipefail
if [[ -z "${BASH_VERSION:-}" ]]; then exec bash "$0" "$@"; fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/tools/common.sh"

VENV_DIR="$ROOT_DIR/venv/p0_env"
SITE="$VENV_DIR/lib/python3.10/site-packages"
OUT="$ROOT_DIR/env_gpu.sh"

if [[ ! -d "$SITE" ]]; then
  p0_die "找不到 site-packages：$SITE（先跑 gpu.sh 安装依赖）"
fi

# Collect CUDA-ish libs shipped by pip nvidia wheels (if present).
paths=()
while IFS= read -r -d '' d; do
  paths+=("$d")
done < <(find "$SITE/nvidia" -maxdepth 2 -type d -name lib -print0 2>/dev/null || true)

# torch also ships libs
if [[ -d "$SITE/torch/lib" ]]; then
  paths+=("$SITE/torch/lib")
fi

if [[ "${#paths[@]}" -eq 0 ]]; then
  p0_log "[ld] 未发现 venv 内自带的 nvidia/torch lib 目录；不生成 env_gpu.sh。"
  exit 0
fi

# Unique, preserve order.
uniq=()
for p in "${paths[@]}"; do
  skip=0
  for q in "${uniq[@]}"; do
    [[ "$p" == "$q" ]] && skip=1 && break
  done
  [[ "$skip" -eq 0 ]] && uniq+=("$p")
done

prefix="$(IFS=:; echo "${uniq[*]}")"

cat > "$OUT" <<EOF
# Auto-generated by tools/fix_ld_library_path.sh
# Usage: source ./env_gpu.sh
export VENV_DIR="$VENV_DIR"
export PATH="\$VENV_DIR/bin:\$PATH"
export LD_LIBRARY_PATH="$prefix:\${LD_LIBRARY_PATH:-}"
EOF

p0_log "[ld] wrote $OUT"
